insert into public.exam_families (code, name, authority, description) values
('gce_ol', 'Cameroon GCE Ordinary Level', 'Cameroon General Certificate of Education Board', 'Ordinary Level national examination papers and corrections.'),
('gce_al', 'Cameroon GCE Advanced Level', 'Cameroon General Certificate of Education Board', 'Advanced Level national examination papers and corrections.'),
('hnd', 'Cameroon Higher National Diploma', 'MINESUP Cameroon', 'National HND papers across business, engineering, health, agriculture and other fields.'),
('bts', 'Cameroon Brevet de Technicien Supérieur', 'MINESUP Cameroon', 'National BTS papers across commercial, technical, communication and service fields.'),
('probatoire', 'Cameroon Probatoire', 'Cameroon Ministry of Secondary Education / examination bodies', 'General and technical Probatoire examination papers.'),
('bepc', 'Cameroon BEPC', 'Cameroon Ministry of Secondary Education', 'BEPC examination papers and corrections.'),
('other', 'Other Cameroon examinations', 'Cameroon examination authorities', 'Reserved for future verified examination families.')
on conflict (code) do nothing;

insert into public.departments (exam_family_id, code, name, stream)
select f.id, d.code, d.name, d.stream
from (values
('gce_ol','0505','Accounting','Commercial'),('gce_ol','0510','Biology','Science'),('gce_ol','0515','Chemistry','Science'),('gce_ol','0520','Commerce','Commercial'),('gce_ol','0525','Economics','Commercial'),('gce_ol','0530','English Language','General'),('gce_ol','0535','Literature in English','Arts'),('gce_ol','0540','Food and Nutrition','Home Economics'),('gce_ol','0545','French','General'),('gce_ol','0550','Geography','Arts'),('gce_ol','0560','History','Arts'),('gce_ol','0562','Citizenship Education','General'),('gce_ol','0565','Human Biology','Science'),('gce_ol','0570','Mathematics','Science'),('gce_ol','0575','Additional Mathematics','Science'),('gce_ol','0580','Physics','Science'),('gce_ol','0585','Religious Studies','Arts'),('gce_ol','0590','Logic','Arts'),('gce_ol','0595','Computer Science','Technology'),
('gce_al','0705','Accounting','Commercial'),('gce_al','0710','Biology','Science'),('gce_al','0715','Chemistry','Science'),('gce_al','0725','Economics','Commercial'),('gce_al','0730','English Language','General'),('gce_al','0735','Literature in English','Arts'),('gce_al','0740','Food Science and Nutrition','Science'),('gce_al','0745','French','General'),('gce_al','0750','Geography','Arts'),('gce_al','0755','Geology','Science'),('gce_al','0760','History','Arts'),('gce_al','0765','Pure Mathematics with Mechanics','Science'),('gce_al','0770','Pure Mathematics with Statistics','Science'),('gce_al','0775','Further Mathematics','Science'),('gce_al','0780','Physics','Science'),('gce_al','0785','Religious Studies','Arts'),('gce_al','0790','Philosophy','Arts'),('gce_al','0795','Computer Science','Technology'),('gce_al','0796','Information and Communication Technology','Technology'),
('hnd','ACY','Accountancy','Business, Finance and Management'),('hnd','AFI','Accounting and Finance','Business, Finance and Management'),('hnd','BF','Banking and Finance','Business, Finance and Management'),('hnd','MG','Management','Business, Finance and Management'),('hnd','EEE-EPS','Electrical and Electronics Engineering - Electrical Power Systems','Engineering and Technology'),('hnd','EEE-TEL','Electrical and Electronics Engineering - Telecommunications','Engineering and Technology'),('hnd','CVE','Civil Engineering','Engineering and Technology'),('hnd','CPE','Computer Engineering','Engineering and Technology'),('hnd','NUS','Nursing','Health and Medical'),('hnd','MLS','Medical Laboratory Sciences','Health and Medical'),('hnd','MIT','Medical Imaging Technology','Health and Medical'),('hnd','DTH','Dental Therapy','Health and Medical'),('hnd','MID','Midwifery','Health and Medical'),('hnd','OPT','Clinical Optometry','Health and Medical'),('hnd','PHY','Physiotherapy','Health and Medical'),('hnd','NUD','Nutrition and Dietetics','Health and Medical'),
('bts','AC','Action Commerciale','Commercial and Management'),('bts','CG','Comptabilité et Gestion des Entreprises','Commercial and Management'),('bts','ASS','Assurances','Commercial and Management'),('bts','BA','Banque','Commercial and Management'),('bts','CI','Commerce International','Commercial and Management'),('bts','IG','Informatique de Gestion','Technology'),('bts','GC','Génie Civil','Engineering and Technology'),('bts','ELN','Électronique','Engineering and Technology'),('bts','ET','Électrotechnique','Engineering and Technology'),('bts','HR','Hôtellerie-Restauration','Tourism and Hospitality'),('bts','TOUR','Tourisme','Tourism and Hospitality'),
('bepc','MATH','Mathematics','General'),('bepc','PCT','Physics-Chemistry-Technology','General'),('bepc','SVT','Life and Earth Sciences','General'),('bepc','HIST','History','General'),('bepc','GEO','Geography','General'),('bepc','CIV','Civic Education','General'),('bepc','GER','German','General'),('probatoire','A-C-D-TI','General and Technical Probatoire','General and Technical')
) as d(family_code, code, name, stream)
join public.exam_families f on f.code = d.family_code
on conflict (exam_family_id, name) do nothing;

insert into public.paper_sources (code, name, url, source_type, years_claimed, access_notes, rights_status) values
('official_gce_ol','Cameroon GCE Board - Ordinary Level','https://camgceb.org/examinations/gce-ordinary-level/','official',null,'Official subject and paper-structure reference; no public past-paper files were exposed.','official_publication'),
('official_gce_al','Cameroon GCE Board - Advanced Level','https://camgceb.org/examinations/gce-advanced-level/','official',null,'Official subject and code reference; no public past-paper files were exposed.','official_publication'),
('official_gce_past','Cameroon GCE Board - Past Questions and Others','https://camgceb.org/past-questions-and-others/','official',null,'Official past-questions portal currently exposes no visible paper inventory in the verified page.','official_publication'),
('meetlearn_ol','MeetLearn - Ordinary Level archive','https://meetlearn.com/downloads/category/19-ordinary-level','public_index','multi-year','Public categorized archive with uneven subject/year counts; individual downloads and rights require verification.','unknown'),
('meetlearn_gce','MeetLearn - Past GCE Questions','https://meetlearn.com/downloads/category/11-past-gce-questions','public_index','multi-year','Public GCE download category; some files use portal or login flows.','unknown'),
('gcerevision_ol','Cameroon GCE Revision - O Level archive','https://cameroongcerevision.com/o-level/','third_party_portal','2000-latest','Public subject archive; availability is uneven and licensing is not stated.','unknown'),
('gcerevision_al','Cameroon GCE Revision - A Level archive','https://cameroongcerevision.com/a-level/','third_party_portal','2000-latest','Public subject/year pages with some unlinked or unavailable entries.','unknown'),
('official_minesup_dauq','MINESUP DAUQ public directory','https://www.minesup.gov.cm/site/DAUQ/','official','2017+','Official directory of examination notices, schedules and some result files; not a complete question-paper archive.','official_publication'),
('official_hnd_2017','MINESUP HND June-July 2017 notice','https://www.minesup.gov.cm/DAUQ/HND-june-july_2017.pdf','official','2017','Official HND schedule/structure reference, not question papers.','official_publication'),
('cameroonhnd','CMR HND Platform question library','https://www.cameroonhnd.com/','third_party_portal','2021+','Advertises verified past questions, but downloads are behind account/dashboard access.','permission_required'),
('unee_acc','UNEE HND Accountancy index','https://uneeapp.online/hnd-past-questions/acc/','app','2020-2026','Public index claims 21 papers across 7 years; files are app-gated.','permission_required'),
('scribd_hnd_eps_2021','Scribd - HND Electrical Power Systems 2021','https://www.scribd.com/document/735337559/2021-HND-QUESTIONS-ELECTRICAL-FILE-1','viewer','2021','Public preview identifies Circuit Theory and related HND material; full access is gated and uploader rights are unverified.','restricted'),
('gcerevision_hnd_nursing_2018','Cameroon GCE Revision - HND 2018 Nursing','https://cameroongcerevision.com/higher-national-diploma-2018-nursing-specialty/','direct_pdf','2018','Public nursing page and linked compilation; no explicit redistribution permission.','permission_required'),
('gcerevision_hnd_nursing_2024','Cameroon GCE Revision - HND June Nursing 2024 PDF','https://cameroongcerevision.com/wp-content/uploads/2025/05/HND-JUNE-NURSING-2024.pdf','direct_pdf','2024','Direct public PDF verified for Nursing Sciences, Mother and Child Health and All-Specialties English.','permission_required'),
('bts_cameroon_desk','Cameroon Desk Academy - BTS archive','https://cameroondeskacademy.com/bts-cameroun-telechargez-les-epreuves-des-annees-precedentes/','commercial','2018-2025','Paid archive claims 242 papers and 102+ specialties; not independently verified paper-by-paper.','permission_required'),
('mongosukulu_bepc','MongoSukulu - BEPC archive','https://www.mongosukulu.com/index.php/telechargement/bepc/','public_index','2010-2021','Year folders and counts are publicly listed; completeness and rights are not established.','unknown'),
('mongosukulu_probatoire','MongoSukulu - Probatoire general archive','https://www.mongosukulu.com/index.php/telechargement/probatoire/probatoiregeneral/','public_index','2010-2021','Year folders are publicly listed; completeness and rights are not established.','unknown'),
('easymaths_bepc','Easy-maths - BEPC catalog','https://easy-maths.org/index.php?option=com_docman&Itemid=81','public_index','2010-2015','Public catalog with downloadable entries; no license statement found.','unknown'),
('camerecole_examens','CamerEcole - searchable examinations portal','https://www.camerecole.org/examens.html','public_index','2010-2025','Searchable Probatoire/BEPC portal with year, subject, series and type filters; HTML content and availability vary.','unknown'),
('orniformation_bepc_svt','Orniformation - BEPC SVT archive','https://orniformation.com/index.php/fr/extensions/plus-de-telechargement/category/12-bepc-cameroun-sujet-derniers-sujets-ou-anciennes-epreuves-de-science-svt-du-cameroun-a-telecharger-gratuitement','public_index','2010-2017','Public category exposes selected SVT papers and corrections; rights are unstated.','unknown'),
('gcerevision_probatoire_2016','Cameroon GCE Revision - Probatoire English 2016 PDF','https://cameroongcerevision.com/wp-content/uploads/2018/08/English-Language-2016.pdf','direct_pdf','2016','Direct PDF verified for Probatoire/Probatoire de BT English; rights are unstated.','permission_required')
on conflict (code) do nothing;

insert into public.papers (exam_family_id, department_id, source_id, year, session, series, subject, paper_number, title, paper_type, language, file_url, availability, verification_notes)
select f.id, d.id, s.id, p.year, p.session, p.series, p.subject, p.paper_number, p.title, p.paper_type, p.language, p.file_url, p.availability, p.notes
from (values
('gce_ol','0570','meetlearn_ol',2010,'June','','Physics','2','GCE O Level Physics Paper 2 June 2010','question','English','https://meetlearn.com/downloads/download/201-physics-ol-2010-p2','verified_page','MeetLearn record verified; portal download endpoint, direct PDF rights not verified.'),
('gce_ol','0525','meetlearn_ol',2018,'June','','Economics','1','GCE O Level Economics Paper 1 2018','question','English','https://meetlearn.com/downloads/download/90-paper-1/198-economics-2018-paper-1','verified_page','MeetLearn record verified; portal download endpoint.'),
('gce_ol','0515','meetlearn_ol',2015,'June','','Chemistry','1','GCE O Level Chemistry Paper 1 June 2015','question','English','https://www.meetlearn.com/downloads/download/119-paper1/343-ol-chem-2015-p1','verified_page','MeetLearn record verified; portal download endpoint.'),
('gce_ol','0560','meetlearn_ol',2015,'June','','History','1','GCE O Level History Paper 1 2015','question','English','https://meetlearn.com/downloads/summary/84-paper-1/403-his-ol-p1-2015','indexed','Index record verified; source points externally and direct file was not confirmed.'),
('hnd','EEE-EPS','scribd_hnd_eps_2021',2021,'June','','Circuit Theory','','HND Electrical Power Systems Circuit Theory 2021','question','English','https://www.scribd.com/document/735337559/2021-HND-QUESTIONS-ELECTRICAL-FILE-1','gated','Public preview exposes identifiable national-exam material; full access is gated.'),
('hnd','NUS','gcerevision_hnd_nursing_2018',2018,'June','','Nursing Basic Sciences','','HND Nursing Basic Sciences 2018','question','English','https://cameroongcerevision.com/higher-national-diploma-2018-nursing-specialty/','verified_page','Public page and linked compilation; rights not established.'),
('hnd','NUS','gcerevision_hnd_nursing_2024',2024,'June','','Nursing Sciences','','HND Nursing Sciences June 2024','question','English','https://cameroongcerevision.com/wp-content/uploads/2025/05/HND-JUNE-NURSING-2024.pdf','verified_pdf','Direct public PDF verified.'),
('hnd','NUS','gcerevision_hnd_nursing_2024',2024,'June','','Mother and Child Health','','HND Nursing Mother and Child Health June 2024','question','English','https://cameroongcerevision.com/wp-content/uploads/2025/05/HND-JUNE-NURSING-2024.pdf','verified_pdf','Direct public PDF verified.'),
('bepc','SVT','orniformation_bepc_svt',2010,'June','','Life and Earth Sciences','','BEPC SVT 2010','question','French','https://orniformation.com/index.php/fr/extensions/plus-de-telechargement/download/12-bepc-cameroun-sujet-derniers-sujets-ou-anciennes-epreuves-de-science-svt-du-cameroun-a-telecharger-gratuitement/312-orniformation-epreuve-svt-bepc-session-2010','verified_pdf','Public download entry verified; rights not established.'),
('probatoire','A-C-D-TI','gcerevision_probatoire_2016',2016,'June','A-C-D-TI','English Language','','Probatoire English Language 2016','question','English','https://cameroongcerevision.com/wp-content/uploads/2018/08/English-Language-2016.pdf','verified_pdf','Direct PDF verified; includes Probatoire technical and BT sections.'),
('probatoire','A-C-D-TI','camerecole_examens',2015,'June','D-TI','Mathematics','','Probatoire Mathematics D/TI 2015','question','French','https://www.camerecole.org/examens/211-epreuve-de-mathematiques-aux-probatoire-d-et-ti-2015.html','verified_page','Public HTML exam page verified.'),
('probatoire','A-C-D-TI','camerecole_examens',2020,'June','D-TI','Mathematics','','Probatoire Mathematics D/TI 2020','question','French','https://www.camerecole.org/examens/939-epreuve-de-mathematiques-au-probatoire-d-et-ti-2020.html','verified_page','Public HTML exam page verified.')
) as p(family_code, dept_code, source_code, year, session, series, subject, paper_number, title, paper_type, language, file_url, availability, notes)
join public.exam_families f on f.code = p.family_code
left join public.departments d on d.exam_family_id = f.id and d.code = p.dept_code
join public.paper_sources s on s.code = p.source_code
on conflict (exam_family_id, year, session, series, subject, paper_number, paper_type) do nothing;
